USE Master;
GO
CREATE MASTER KEY ENCRYPTION
BY PASSWORD='InsertStrongPasswordHere';
GO

CREATE CERTIFICATE TDE_Cert
WITH
SUBJECT='Database_Encryption';
GO

USE <DB>
GO

CREATE DATABASE ENCRYPTION KEY
WITH ALGORITHM = AES_256
ENCRYPTION BY SERVER CERTIFICATE TDE_Cert;
GO

ALTER DATABASE <DB>
SET ENCRYPTION ON;
GO

BACKUP CERTIFICATE TDE_Cert
TO FILE = '/tmp/TDE_Cert'
WITH PRIVATE KEY (file='/temp/TDE_CertKey.pvk',
ENCRYPTION BY PASSWORD='InsertStrongPasswordHere')