name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: cgaspard/mssql-docker

    - name: Get the date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d.%H%M')"
    
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          cjgaspard/mssql-server:latest
          cjgaspard/mssql-server:${{ steps.date.outputs.date }}
          cjgaspard/mssql-server:2022-ubuntu-20.04